/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const Order = IDL.Record({
  'deliveryAddress' : IDL.Opt(IDL.Text),
  'senderPlace' : IDL.Text,
  'queryType' : IDL.Text,
  'agriKitSeeds' : IDL.Opt(IDL.Text),
  'agriKitFertilizer' : IDL.Opt(IDL.Text),
  'agriKitComments' : IDL.Opt(IDL.Text),
  'timestamp' : Timestamp,
  'senderName' : IDL.Text,
  'paymentMode' : IDL.Text,
  'agriKitOrganic' : IDL.Bool,
  'senderAddress' : IDL.Text,
  'refId' : IDL.Text,
});
export const OrderInput = IDL.Record({
  'deliveryAddress' : IDL.Opt(IDL.Text),
  'senderPlace' : IDL.Text,
  'queryType' : IDL.Text,
  'agriKitSeeds' : IDL.Opt(IDL.Text),
  'agriKitFertilizer' : IDL.Opt(IDL.Text),
  'agriKitComments' : IDL.Opt(IDL.Text),
  'senderName' : IDL.Text,
  'paymentMode' : IDL.Text,
  'agriKitOrganic' : IDL.Bool,
  'senderAddress' : IDL.Text,
});

export const idlService = IDL.Service({
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'submitOrder' : IDL.Func([OrderInput], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const Order = IDL.Record({
    'deliveryAddress' : IDL.Opt(IDL.Text),
    'senderPlace' : IDL.Text,
    'queryType' : IDL.Text,
    'agriKitSeeds' : IDL.Opt(IDL.Text),
    'agriKitFertilizer' : IDL.Opt(IDL.Text),
    'agriKitComments' : IDL.Opt(IDL.Text),
    'timestamp' : Timestamp,
    'senderName' : IDL.Text,
    'paymentMode' : IDL.Text,
    'agriKitOrganic' : IDL.Bool,
    'senderAddress' : IDL.Text,
    'refId' : IDL.Text,
  });
  const OrderInput = IDL.Record({
    'deliveryAddress' : IDL.Opt(IDL.Text),
    'senderPlace' : IDL.Text,
    'queryType' : IDL.Text,
    'agriKitSeeds' : IDL.Opt(IDL.Text),
    'agriKitFertilizer' : IDL.Opt(IDL.Text),
    'agriKitComments' : IDL.Opt(IDL.Text),
    'senderName' : IDL.Text,
    'paymentMode' : IDL.Text,
    'agriKitOrganic' : IDL.Bool,
    'senderAddress' : IDL.Text,
  });
  
  return IDL.Service({
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'submitOrder' : IDL.Func([OrderInput], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };